// AI service layer — pluggable, real free-tier cloud APIs, called directly from
// the browser. API keys come from environment variables (set in .env locally or
// in the Vercel dashboard for production).
//
//   OCR.space   -> raw text + per-word bounding boxes (boundary visualization)
//   Gemini      -> multimodal OCR + JSON structuring (free tier)
//   Groq        -> fast text -> strict JSON structuring (free tier)
//
// All three expose CORS-enabled REST endpoints usable from a static SPA.

export const EXTRACTION_SCHEMA = {
  is_same_commodity: 'boolean (true if all provided image text belongs to the SAME packaged product, false if images describe 2 DIFFERENT products)',
  commodity_mismatch_reason: 'string|null (if false, explain the mismatch e.g. Image 1 is Parle-G but Image 2 is Tata Salt)',
  product_name: 'string|null',
  common_generic_name: 'string|null',
  manufacturer_packer_importer: 'string|null (full name + address as printed)',
  has_full_address: 'boolean (true only if a city/state or PIN code is present)',
  net_quantity_raw: 'string|null (exactly as printed, e.g. "Net Wt. 500 g")',
  net_quantity_value: 'number|null (numeric part only, e.g. 500)',
  net_quantity_unit: 'one of g,kg,mg,ml,l,cm,m,sqcm,sqm,N,U or null',
  mrp_raw: 'string|null (full MRP line as printed)',
  mrp_value: 'number|null',
  mrp_tax_inclusive: 'boolean (true if it says inclusive of all taxes)',
  mfg_date_raw: 'string|null (month/year of manufacture, packing or import)',
  consumer_care_raw: 'string|null (customer care / complaint contact)',
  country_of_origin: 'string|null',
  is_imported: 'boolean',
  dimensions_raw: 'string|null (size/dimensions if printed)',
  commodity_category: 'string|null (e.g. biscuits, tea, soap, bedsheet, cement)',
  commodity_type: 'string|null (food | cosmetic | agricultural_produce | general)',
  buyer_type: 'string (retail | industrial_consumer | institutional_consumer)',
}

const PROMPT = `You are a data-extraction engine for Indian Legal Metrology label compliance.
From the packaged-commodity label text below, extract EXACTLY this JSON object and NOTHING else.
Do not judge compliance. Only transcribe what is printed. Use null when a field is absent.
Schema (value = description of what to put):
${JSON.stringify(EXTRACTION_SCHEMA, null, 2)}
Return only minified valid JSON.`

export function fileToDataURL(file) {
  return new Promise((resolve, reject) => {
    const r = new FileReader()
    r.onload = () => resolve(r.result)
    r.onerror = reject
    r.readAsDataURL(file)
  })
}

export function stripToJSON(text) {
  if (!text) return null
  // 1. Strip reasoning / think tags generated by models like DeepSeek / Qwen
  let clean = text.replace(/<think>[\s\S]*?<\/think>/gi, '').trim()

  // 2. Extract content from markdown code fences if present
  const jsonBlockMatch = clean.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)
  if (jsonBlockMatch && jsonBlockMatch[1]) {
    clean = jsonBlockMatch[1].trim()
  }

  // 3. Find outermost JSON object braces
  const s = clean.indexOf('{')
  const e = clean.lastIndexOf('}')
  if (s === -1 || e === -1 || e < s) return null

  try {
    return JSON.parse(clean.slice(s, e + 1))
  } catch {
    return null
  }
}

export function getValidGoogleKey(k1, k2) {
  const isValid = (k) => k && typeof k === 'string' && k.trim().length > 15
  if (isValid(k1)) return k1.trim()
  if (isValid(k2)) return k2.trim()
  return ''
}

// ---------- OCR.space : raw text + word bounding boxes ----------------------
// ---------- OCR.space : raw text + word bounding boxes ----------------------
export async function ocrSpace(file, key = 'helloworld') {
  const fd = new FormData()
  fd.append('file', file)
  fd.append('language', 'eng')
  fd.append('isOverlayRequired', 'true')
  fd.append('OCREngine', '2')
  fd.append('scale', 'false') // Keep scale false so coordinates strictly match natural image pixels
  const res = await fetch('https://api.ocr.space/parse/image', {
    method: 'POST',
    headers: { apikey: key },
    body: fd,
  })
  if (!res.ok) throw new Error(`OCR.space HTTP ${res.status}`)
  const data = await res.json()
  if (data.IsErroredOnProcessing) {
    throw new Error((data.ErrorMessage && data.ErrorMessage[0]) || 'OCR.space error')
  }
  const parsed = data.ParsedResults?.[0]
  const rawText = parsed?.ParsedText || ''
  const words = []
  const lines = parsed?.TextOverlay?.Lines || []
  for (const ln of lines) {
    for (const w of ln.Words || []) {
      words.push({
        text: w.WordText,
        x: w.Left, y: w.Top, w: w.Width, h: w.Height,
      })
    }
  }
  return { rawText, words, source: 'OCR.space (Engine 2)' }
}

// ---------- Google Cloud Vision : OCR + word bounding boxes -----------------
export async function googleVision(file, key) {
  if (!key) throw new Error('Google Vision API key missing (add it in Settings).')
  const dataUrl = await fileToDataURL(file)
  const b64 = dataUrl.split(',')[1]
  const body = {
    requests: [{
      image: { content: b64 },
      features: [{ type: 'DOCUMENT_TEXT_DETECTION' }],
      imageContext: { languageHints: ['en', 'hi'] },
    }],
  }
  const res = await fetch(`https://vision.googleapis.com/v1/images:annotate?key=${key}`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body),
  })
  if (!res.ok) throw new Error(`Google Vision HTTP ${res.status}: ${(await res.text()).slice(0, 180)}`)
  const data = await res.json()
  const r = data?.responses?.[0]
  if (r?.error) throw new Error(`Google Vision: ${r.error.message}`)
  const rawText = r?.fullTextAnnotation?.text || r?.textAnnotations?.[0]?.description || ''
  const words = []
  const pages = r?.fullTextAnnotation?.pages || []
  for (const page of pages) {
    const pWidth = page.width || 1
    const pHeight = page.height || 1
    for (const block of page.blocks || []) {
      for (const para of block.paragraphs || []) {
        for (const word of para.words || []) {
          const v = word.boundingBox?.vertices || []
          if (v.length < 3) continue
          const xs = v.map((p) => p.x || 0)
          const ys = v.map((p) => p.y || 0)
          const minX = Math.min(...xs), minY = Math.min(...ys)
          const w = Math.max(...xs) - minX
          const h = Math.max(...ys) - minY
          words.push({
            text: (word.symbols || []).map((s) => s.text).join(''),
            x: minX,
            y: minY,
            w,
            h,
            pageWidth: pWidth,
            pageHeight: pHeight,
            leftPct: (minX / pWidth) * 100,
            topPct: (minY / pHeight) * 100,
            widthPct: (w / pWidth) * 100,
            heightPct: (h / pHeight) * 100,
          })
        }
      }
    }
  }
  return { rawText, words, source: 'Google Cloud Vision' }
}

const DEFAULT_GEMINI_MODEL = import.meta.env.VITE_GEMINI_MODEL || 'gemini-3.6-flash'
const DEFAULT_GROQ_MODEL = import.meta.env.VITE_GROQ_MODEL || 'groq/compound'

// ---------- Gemini : multimodal OCR + boxes ---------------------------------
export async function geminiOCR(file, key, model = DEFAULT_GEMINI_MODEL) {
  if (!key) throw new Error('Gemini API key missing (add it in Settings).')
  const targetModel = model || DEFAULT_GEMINI_MODEL
  const dataUrl = await fileToDataURL(file)
  const b64 = dataUrl.split(',')[1]
  const mime = dataUrl.slice(5, dataUrl.indexOf(';'))
  const body = {
    contents: [{
      parts: [
        { text: 'Transcribe ALL text visible on this product package label, preserving line breaks. Output plain text only, no commentary.' },
        { inline_data: { mime_type: mime, data: b64 } },
      ],
    }],
  }
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${targetModel}:generateContent?key=${key}`
  const res = await fetch(url, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body),
  })
  if (!res.ok) throw new Error(`Gemini HTTP ${res.status}: ${(await res.text()).slice(0, 160)}`)
  const data = await res.json()
  const rawText = data?.candidates?.[0]?.content?.parts?.map((p) => p.text).join('') || ''
  return { rawText, words: [], source: `Gemini (${targetModel})` }
}

// ---------- Structuring: text -> schema JSON --------------------------------
export async function geminiStructure(rawText, key, model = DEFAULT_GEMINI_MODEL) {
  if (!key) throw new Error('Gemini API key missing (get a free key at https://aistudio.google.com/app/apikey).')
  const trimmedText = (rawText || '').slice(0, 4000)
  const targetModel = model || DEFAULT_GEMINI_MODEL

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${targetModel}:generateContent?key=${key}`
  const body = {
    contents: [{ parts: [{ text: `${PROMPT}\n\nLABEL TEXT:\n"""${trimmedText}"""` }] }],
    generationConfig: { temperature: 0, responseMimeType: 'application/json' },
  }
  const res = await fetch(url, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body),
  })
  if (!res.ok) {
    const errText = await res.text()
    if (res.status === 403 && errText.includes('API_KEY_SERVICE_BLOCKED')) {
      throw new Error('Gemini API permission denied. Enable Generative Language API on this key or get a free key from https://aistudio.google.com/app/apikey')
    }
    if (res.status === 404) {
      throw new Error(`Gemini model "${targetModel}" not found. Check VITE_GEMINI_MODEL in .env`)
    }
    if (res.status === 400) {
      throw new Error(`Gemini rejected the request (400). Verify your API key is valid: ${errText.slice(0, 120)}`)
    }
    throw new Error(`Gemini HTTP ${res.status}: ${errText.slice(0, 160)}`)
  }
  const data = await res.json()
  const text = data?.candidates?.[0]?.content?.parts?.map((p) => p.text).join('') || ''
  const parsed = stripToJSON(text)
  if (parsed) return parsed
  throw new Error('Gemini returned a response but it contained no valid JSON.')
}

export async function groqStructure(rawText, key, model = DEFAULT_GROQ_MODEL) {
  if (!key) throw new Error('Groq API key missing (add it in Settings).')
  const targetModel = model || DEFAULT_GROQ_MODEL
  const trimmedText = (rawText || '').slice(0, 3500)
  const payload = {
    model: targetModel,
    temperature: 0,
    messages: [
      { role: 'system', content: PROMPT + '\nReturn ONLY a valid JSON object.' },
      { role: 'user', content: `LABEL TEXT:\n"""${trimmedText}"""\nOutput valid JSON:` },
    ],
  }

  // Attempt 1: Strict JSON object mode
  try {
    const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
      body: JSON.stringify({ ...payload, response_format: { type: 'json_object' } }),
    })
    if (res.ok) {
      const data = await res.json()
      const parsed = stripToJSON(data?.choices?.[0]?.message?.content)
      if (parsed) return parsed
      console.warn('[Groq] json_object mode returned unparseable content:', data?.choices?.[0]?.message?.content?.slice(0, 200))
    } else {
      const errText = await res.text()
      console.warn(`[Groq] json_object mode HTTP ${res.status}:`, errText.slice(0, 160))
    }
  } catch (e) {
    console.warn('[Groq] json_object mode error:', e.message)
  }

  // Attempt 2: Standard completion with manual JSON extraction (resilient against 400 validation errors)
  const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
    body: JSON.stringify(payload),
  })
  if (!res.ok) {
    const errText = await res.text()
    throw new Error(`Groq HTTP ${res.status} (model: ${targetModel}): ${errText.slice(0, 160)}`)
  }
  const data = await res.json()
  const raw = data?.choices?.[0]?.message?.content
  const parsed = stripToJSON(raw)
  if (!parsed) {
    console.warn('[Groq] Could not parse JSON from response:', raw?.slice(0, 300))
    throw new Error(`Groq (model: ${targetModel}) did not return valid JSON. Check VITE_GROQ_MODEL in .env`)
  }
  return parsed
}

// ---------- Heuristic fallback (no LLM key) ---------------------------------
export function heuristicStructure(rawText) {
  const t = rawText || ''
  const line = (re) => (t.match(re) || [])[0] || null
  const mrp = line(/(m\.?r\.?p\.?|maximum retail price)[^\n]*/i)
  const qtyMatch = t.match(/(\d+(?:\.\d+)?)\s*(kg|g|mg|ml|l|litre|litres|gram|grams)\b/i)
  let unit = qtyMatch ? qtyMatch[2].toLowerCase() : null
  if (unit === 'litre' || unit === 'litres') unit = 'l'
  if (unit === 'gram' || unit === 'grams') unit = 'g'
  return {
    product_name: t.split('\n').find((l) => l.trim().length > 2)?.trim() || null,
    common_generic_name: null,
    manufacturer_packer_importer: line(/(mfd|manufactured|marketed|packed)\s*by[^\n]*/i),
    has_full_address: /\b\d{6}\b/.test(t),
    net_quantity_raw: line(/(net\s*(wt|weight|qty|quantity|vol)[^\n]*)/i) || (qtyMatch ? qtyMatch[0] : null),
    net_quantity_value: qtyMatch ? parseFloat(qtyMatch[1]) : null,
    net_quantity_unit: unit,
    mrp_raw: mrp,
    mrp_value: mrp ? parseFloat((mrp.match(/(\d+(?:\.\d+)?)/) || [])[1]) || null : null,
    mrp_tax_inclusive: /inclusive of all tax/i.test(t),
    mfg_date_raw: line(/(mfg|mfd|manufactured|packed|pkd)[^\n]*\d{2,4}/i),
    consumer_care_raw: line(/(customer|consumer)\s*care[^\n]*/i),
    country_of_origin: line(/country of origin[^\n]*/i),
    is_imported: /imported|country of origin/i.test(t),
    dimensions_raw: null,
    commodity_category: null,
    commodity_type: 'general',
    buyer_type: 'retail',
  }
}

// ---------- Orchestrator ----------------------------------------------------
// Flow: Google Vision (OCR) -> Google Gemini Flash (Primary LLM Structuring).
// Supports at most 3 files (e.g. Front panel + Back panel + Side panel) of the same product.
export async function extractAll(filesInput, settings) {
  const files = Array.isArray(filesInput) ? filesInput.slice(0, 3) : [filesInput]
  if (!files.length || !files[0]) throw new Error('No image file provided for extraction.')

  const engine = settings.ocrEngine || (settings.visionKey ? 'vision' : 'ocrspace')
  let combinedRawText = ''
  let allWords = []
  let ocrSources = []
  let warnMsg = ''

  // 1) OCR — process up to 3 uploaded images
  for (let i = 0; i < files.length; i++) {
    const f = files[i]
    let ocr
    if (engine === 'vision' && settings.visionKey) {
      try { ocr = await googleVision(f, settings.visionKey) }
      catch (e) { ocr = await ocrSpace(f, settings.ocrSpaceKey); warnMsg = `Google Vision failed on image ${i + 1}, used OCR.space: ` + e.message }
    } else {
      ocr = await ocrSpace(f, settings.ocrSpaceKey)
      if (engine === 'vision' && i === 0) warnMsg = 'No Google Vision key set — used OCR.space.'
    }

    if (files.length > 1) {
      combinedRawText += `--- IMAGE ${i + 1} (${f.name}) ---\n${ocr.rawText || ''}\n\n`
    } else {
      combinedRawText += (ocr.rawText || '')
    }

    if (ocr.words && Array.isArray(ocr.words)) {
      allWords.push(...ocr.words.map((w) => ({ ...w, imageIndex: i + 1 })))
    }
    if (ocr.source) ocrSources.push(ocr.source)
  }

  const ocrResult = {
    rawText: combinedRawText.trim(),
    words: allWords,
    source: [...new Set(ocrSources)].join(' + '),
    warn: warnMsg,
  }

  // 2) Structuring — Gemini Flash as MAIN, Groq as FALLBACK, then Heuristic
  const geminiKey = getValidGoogleKey(settings.geminiKey, settings.visionKey)
  const isGeminiKeyValid = !!geminiKey
  let structured = null
  let structuringSource = ''
  let isFallback = false
  let fallbackReason = ''

  const multiNotice = files.length > 1
    ? `NOTE: You are given text from ${files.length} images/panels of a packaged commodity. FIRST verify if both images belong to the SAME product. If Image 1 and Image 2 describe DIFFERENT products (e.g. Parle-G vs Tata Salt), set "is_same_commodity": false and explain in "commodity_mismatch_reason". Otherwise set "is_same_commodity": true.`
    : ''

  const promptText = multiNotice ? `${ocrResult.rawText}\n\n${multiNotice}` : ocrResult.rawText

  // Attempt 1: Gemini Flash (Primary LLM)
  if (isGeminiKeyValid) {
    const gemModel = settings.geminiModel || 'gemini-3.6-flash'
    console.log(`[SmartInspect] Structuring via Gemini model="${gemModel}", key="${geminiKey.slice(0, 6)}…"`)
    try {
      structured = await geminiStructure(promptText, geminiKey, gemModel)
      structuringSource = `Google Gemini (${gemModel})`
    } catch (e) {
      console.error('[SmartInspect] Gemini structuring failed:', e.message)
      fallbackReason = 'Gemini Flash error: ' + e.message
    }
  } else {
    fallbackReason = 'Gemini API key not configured'
  }

  // Attempt 2: Groq (Fallback LLM if Gemini failed)
  if (!structured && settings.groqKey) {
    try {
      structured = await groqStructure(promptText, settings.groqKey, settings.groqModel || 'groq/compound')
      structuringSource = `Groq (${settings.groqModel || 'groq/compound'}) [Fallback]`
      isFallback = true
      fallbackReason = `Gemini unavailable (${fallbackReason}) → Used Groq fallback`
    } catch (e) {
      fallbackReason += ' | Groq fallback error: ' + e.message
    }
  }

  // Attempt 3: Local Heuristic Parser (Final Safety Net)
  if (!structured) {
    structured = heuristicStructure(ocrResult.rawText)
    structuringSource = 'Built-in Heuristic Parser [Fallback]'
    isFallback = true
    fallbackReason = `AI structuring unavailable (${fallbackReason}) → Used local heuristic parser`
  }

  if (isFallback) {
    ocrResult.warn = (ocrResult.warn ? ocrResult.warn + ' | ' : '') + fallbackReason
  }

  // 3) Verification: Check for commodity mismatch if 2 images uploaded
  let isMismatch = false
  let mismatchReason = null

  if (files.length > 1) {
    if (structured.is_same_commodity === false) {
      isMismatch = true
      mismatchReason = structured.commodity_mismatch_reason || 'The 2 uploaded images appear to be from two different packaged commodities.'
    } else {
      // Additional heuristic check on panel texts
      const textParts = ocrResult.rawText.split('--- IMAGE 2')
      if (textParts.length > 1) {
        const p1 = textParts[0].toLowerCase()
        const p2 = textParts[1].toLowerCase()
        const brands = ['parle', 'tata', 'britannia', 'nestle', 'amul', 'haldiram', 'cadbury', 'maggi', 'dabur', 'patanjali', 'dettol', 'dove', 'surf excel', 'fortune', 'aashirvaad']
        const b1 = brands.find((b) => p1.includes(b))
        const b2 = brands.find((b) => p2.includes(b))
        if (b1 && b2 && b1 !== b2) {
          isMismatch = true
          mismatchReason = `Image 1 contains brand "${b1.toUpperCase()}" whereas Image 2 contains brand "${b2.toUpperCase()}". They are different packaged commodities.`
        }
      }
    }
  }

  return {
    ...ocrResult,
    structured,
    structuringSource,
    isFallback,
    fallbackReason: isFallback ? fallbackReason : null,
    isMismatch,
    mismatchReason,
    fileCount: files.length,
  }
}
